### ISSUE TITLE
quarto compatibility?

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#25]
Hi 
Are there any compatibility issues or limitations between the markdown generated by ox-ravel and quarto ? Or is it fully compatible.
thanks
FKG

**Comment by chasberry** [comment]
I haven't used quarto, but as of commit 76a2aaf06a0af25f07a81bc1ae41a5d6eedeae49 it should do so.

As [ox-ravel.org](https://github.com/chasberry/orgmode-accessories/blob/org-9-plus/ox-ravel.org) now explains:

The `'ravel-markdown` exporter will produce [quarto](https://quarto.org) documents. The
`.Rmd` file extension that is produced by default can be changed to
`.qmd` by customizing the entry for `md` in \`org-ravel-style-alist\`.

Let me know if you hit any bumps.

CCB

p.s. Sorry for the delayed response - I was offline for a a few weeks.  :-)

**Comment by fkgruber** [comment]
Hi CCB,
I tried the most recent version of ox-ravel and I tried to export the following orgmode file
```

#+Title:test 
#+BABEL: :exports both :tangle yes  
#+PROPERTY: header-args :exports both :tangle yes :ravel echo=TRUE,eval=TRUE,results='markup',message=FALSE,warning=FALSE,error=FALSE,cache=2, fig.width=10,fig.height=10
#+PROPERTY: header-args:R :session *R*  :tangle yes  :exports both :colnames yes 
#+TODO: TODO(t) | DONE(d) | PARTIALLY(p)  | CANCELED(c)
#+EXPORT_FILE_NAME: 
#+OPTIONS: ^:{}
-----

#+BEGIN_EXPORT yaml
output:
    html_document:
      toc: true
      toc_float: true
      toc_depth: 3
      toc_collapsed: true
      code_fold: show
      theme: flatly
      highlight: tango
#+END_EXPORT
* R Code
#+begin_src R
head(mtcars)
#+end_src
* python code
#+begin_src python
import sys
print("testg")
#+end_src
```
 however the export does not make the python code a code block:
---
# YAML header created by ox-ravel
output:
    html_document:
      toc: true
      toc_float: true
      toc_depth: 3
      toc_collapsed: true
      code_fold: show
      theme: flatly
      highlight: tango
title: test
---
---


# R Code

```{r}
#| echo: TRUE
#| eval: TRUE
#| results: 'markup'
#| message: FALSE
#| warning: FALSE
#| error: FALSE
#| cache: 2
#| fig.width: 10
#| fig.height: 10
head(mtcars)
```


# python code

    import sys
    print("testg")

Quarto is suppose to accept python code  so ir would be great if python codes are also treated as blocks.
